### ISSUE TITLE
Bug in usb_MIDI.c

### ISSUE THREAD

**Issue by apateluk** [MrBlueXav/Dekrispator_v2#10]
Hi
Piano seemed to be recognised, but was having issues with any key presses not being recognised. 

I noticed on line 97 of usb_midi.c - 

`MIDI_Handle =  phost->pActiveClass->pData;`

was commented out. Putting it back in seemed to fix the issue. Is this intentional ?

**Comment by MrBlueXav** [comment]
Fixed !
Thank you very much !
(unintentional typo)
