### ISSUE TITLE
Triggering sounds vs. Sequencer

### ISSUE THREAD

**Issue by botoxparty** [MrBlueXav/Dekrispator_v2#11]
Hey!

Thank you so much for this project it's incredible! Hopefully I can sink my teeth deep enough to contribute something :)

I was noticing that all the sounds are triggered by some kind of step sequencer, is there an easy way to add a trigger to just have a sound on/off state rather than using the step sequencer?

Best,
Adam

**Comment by MrBlueXav** [comment]
Thank you botoxparty !
In new Dekrispatorv3 branch, notes can now be triggered through a midi (compatible) keyboard.
You can also start and stop sequencer with the blue button.
See new Readme.
Best regards
Xav

**Comment by botoxparty** [comment]
❤️
