### ISSUE TITLE
Port to OWL

### ISSUE THREAD

**Issue by pingdynasty** [MrBlueXav/Dekrispator_v2#3]
Hi there, loving your stuff, great work and great imagination.
Would you be interested in porting to the OWL [1]?
Same microcontroller plus stereo codec and another 1Mb fast SRAM to play with.

[1] https://github.com/pingdynasty/OwlProgram

**Comment by MrBlueXav** [comment]
Thank you for your interest !
Sorry I have no time at the moment and I don't own your great OWL pedal...
Best regards

**Comment by pingdynasty** [comment]
Let me know if things change, maybe we can do a trade!
