### ISSUE TITLE
Stopping the sequence & MIDI note ON/OFF response?

### ISSUE THREAD

**Issue by cube48** [MrBlueXav/Dekrispator_v2#4]
Hi @MrBlueXav, 
First of all, thanks a lot for such funny synth! I have it successfully running on STM32F4DISCOVERY board and it nicely responds to MIDI CC's. But I have a question concerning the sequencer. **Is the sequencer all the time ON without the option to stop it?** I tried to change the values of MIDI CC 26 but it was only changing the pattern.

`case 26 : seq_switchMovingSeq(val); break; // toggle sequence mode`

It doesn't response to normal MIDI keyboard action. I would like to use it as a traditional (good sounding!, btw) mono synth which responds to MIDI note ON and OFF events. My coding skills are on bash scripting level only. Yes, I can 'read' C but no way I can program a new stuff. Still, if I try to learn more about it, what (and where) would I have to change to get the standard MIDI note ON/OFF response from your marvellous Dekrispator?

Thanks again!
Jakub

**Comment by GaryA** [comment]
It's been a while, but take a look at this fork to see how to implement MIDI note on/note off handling.
https://github.com/GaryA/Dekrispator_v2/tree/note_on_note_off
Dekrispator uses almost all the memory of the STM32F4 so it's difficult to add too many more functions without having to remove something. It's a starting point...
