### ISSUE TITLE
make us a midi synth please :)

### ISSUE THREAD

**Issue by reaganry** [MrBlueXav/Dekrispator_v2#6]
can you tweak this for us to be a regular note-playing usbhost midi synth? it seems beyond the reach of mortals

**Comment by GaryA** [comment]
Rest assured I am only a mortal :) but I have made a version of Dekrispator that responds to note on/note off messages so it can be played from a keyboard.
Currently you still need to send CC messages to change the synth parameters (or change them in the code!) but it's a start.
https://github.com/GaryA/Dekrispator_v2/tree/note_on_note_off

**Comment by reaganry** [comment]
wow, this is pure gold - a perfect friend for my beatstep. thanks for doing this!

**Comment by MrBlueXav** [comment]
GaryA's work merged  !
See new branch : DekrispatorV3
Dekrispator can now work as a true midi synth.
