### ISSUE TITLE
Fix to usbh_MIDI.c to clear MIDI_HandleTypeDef struct after allocation

### ISSUE THREAD

**Issue by JSB2500** [MrBlueXav/Dekrispator_v2#7]
Dear Xavier

Firstly, many thanks for creating midi_USBH.h/midi_USBH.c!

I found a problem with MIDI_Handle->data_tx_state being essentially a random value, causing my code to try sending MIDI data prematurely. The problem happened with some builds but not others.

The problem is around line 96 of midi_USBH.c. It allocates a MIDI_HandleTypeDef struct but does not zero it. As a result it is full of rubbish that can cause the program to fail.

To solve it, I inserted this line after the memory allocation:
USBH_memset(phost->pActiveClass->pData, 0, sizeof(MIDI_HandleTypeDef));

An alternative solution is to insert this after MIDI_Handle = phost->pActiveClass->pData:
USBH_memset(MIDI_Handle, 0, sizeof(MIDI_HandleTypeDef));

Please incorporate such a fix into the source code.

I hope this is useful.

Thanks again,
John.

**Comment by MrBlueXav** [comment]
Thank you very much for improving my crappy midi host usb driver ! I'll check this soon .

**Comment by MrBlueXav** [comment]
Done !
