### ISSUE TITLE
Best IDE to compile? What about a 12 bit DAC?

### ISSUE THREAD

**Issue by spherical-sound-society** [MrBlueXav/Dekrispator_v2#8]
Quite advanced in arduino and java programming. Would like to step up my game.

I have downloaded and testing platformio.

What´s the best IDE to tweak dekrispator? Would platformio be ok?

Would like to do an alternative version that runs on black pill (smt32f401-f411) and a 12bits stereo DAC (MCP4822). Would it be possible? Any recommendations to follow?

Thanks!!

**Comment by MrBlueXav** [comment]
Currently I'm trying to adapt Dekrispator to STM32CubeIDE.
It's a free Eclipse based IDE from ST and works well.
Don't know anything about platformio, sorry.
Should be quite possible to run on black pill but I can't do it.
Cheers !
Xavier
